### ISSUE TITLE
How can we obtain the set of multi-objective solutions?

### ISSUE THREAD

**Issue by Rohit-Kundu** [pietrobarbiero/evofs#1]
Using the test code, the scores for the best set is obtained. But how can we obtain the whole Pareto front?

**Comment by pietrobarbiero** [comment]
The solutions in the Pareto front are stored in `model.solutions_`, after EvoFS has been trained (i.e. after `model = EvoFS(...)` and `model.fit(X, y)`).

`model.solutions_` is a list of objects of class `inspyred.ec.Individual`. Here you can find all the details from the `inspyred` documentation: [https://pythonhosted.org/inspyred/reference.html?highlight=individual#inspyred.ec.Individual](url)

**Comment by Rohit-Kundu** [comment]
Thank you for your help! I tried stopping the model training midway and printing `model.solutions_` , so it threw an error. It works now.
